# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalmessages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='personalmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='personalmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='PersonalMessage',
        ),
    ]
