# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalmessages', '0004_personalmessage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalmessage',
            name='name',
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
