# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalmessages', '0005_auto_20171106_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
