# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
