# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_auto_20171030_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
