# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_auto_20171030_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.CharField(default='', max_length=30),
        ),
    ]
