# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_post_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='C:\\Users\\Miika\\Desktop\\ConversationApp\\conversationapp\\feeds/media\\profile_image/1.png', upload_to='profile_image'),
        ),
    ]
