# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_auto_20171102_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/media/profile_image/1.png', upload_to='profile_image'),
        ),
    ]
