# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_auto_20171103_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='C:\\Users\\Miika\\Desktop\\ConversationApp\\conversationapp\\feeds/media\\feeds/default_image/1.png', upload_to='profile_image'),
        ),
    ]
