# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_auto_20171106_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='feeds/profile_image/1.png', upload_to='profile_image'),
        ),
    ]
